### PR TITLE
Hotfix/flags

### PR DESCRIPTION
**Pull request by vicxruiz**
# Description

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [x ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ x] There are no merge conflicts

### CODE REVIEW

**Comment by vicxruiz** [comment]
Updated ui on welcome storyboard and main storyboard. Cleaned up some constraint issues on the login page that weren't letting some devices login. Added validation for sign up for each text field. Updated progress tint for requirement cells and bar to better match web. Deleted unused folders and classes for cleaner structure. Followed commands to delete features that weren't in PVD.

**Comment by sameeraleola** [comment]
Tested on simulator and iPhone 7-Plus successfully.

**Comment by ticotheps** [comment]
@vicxruiz , I was able to pull down your branch and test it on my local machine without any build errors. I saw everything on my local machine's simulator that you described in your comment above. The only things I noticed were: (1) on my home screen, I had some trouble knowing where to click to get to the "steps" page for each requirement card because there were no clearly defined borders/shadows on each card, (2) when I navigated to the "steps" page for the 'mock interview' requirement card, upon toggling the checkmark "ON" for a checkbox, I noticed that it resized the card in an odd way that produced extra whitespace. I wasn't sure if those two things were meant to be that way, but I figured that I would at least alert you! Other than those two things, everything else looked great! Nice work, man!
Screen Shot 2019-09-14 at 9 08 02 PM

**Comment by ticotheps** [comment]
@vicxruiz, I noticed that the semver tag was not increased from "v1.1.1" to "v1.1.2" so I just went ahead and did that. See here => https://youtu.be/9tkAPA7DLOA

**Pull request merged**
